CREATE TABLE poi_table (
                           id INT PRIMARY KEY AUTO_INCREMENT,
                           name VARCHAR(255) NOT NULL,
                           description TEXT,
                           lng INT,
                           lat INT
);INSERT INTO poi_table (name, description, lng, lat) VALUES
                                                          ('POI 1', 'Description 1', 123, 456),
                                                          ('POI 2', 'Description 2', 789, 321),
                                                          ('POI 3', 'Description 3', 654, 987),
                                                          ('POI 4', 'Description 4', 111, 222),
                                                          ('POI 5', 'Description 5', 333, 444),
                                                          ('POI 6', 'Description 6', 555, 666),
                                                          ('POI 7', 'Description 7', 777, 888),
                                                          ('POI 8', 'Description 8', 999, 000),
                                                          ('POI 9', 'Description 9', 246, 135),
                                                          ('POI 10', 'Description 10', 789, 654),
                                                          ('POI 11', 'Description 11', 852, 741),
                                                          ('POI 12', 'Description 12', 963, 852),
                                                          ('POI 13', 'Description 13', 147, 258),
                                                          ('POI 14', 'Description 14', 369, 741),
                                                          ('POI 15', 'Description 15', 753, 951),
                                                          ('POI 16', 'Description 16', 852, 963),
                                                          ('POI 17', 'Description 17', 159, 357),
                                                          ('POI 18', 'Description 18', 258, 456),
                                                          ('POI 19', 'Description 19', 357, 654),
                                                          ('POI 20', 'Description 20', 456, 852),
                                                          ('POI 21', 'Description 21', 654, 753),
                                                          ('POI 22', 'Description 22', 753, 951),
                                                          ('POI 23', 'Description 23', 852, 357),
                                                          ('POI 24', 'Description 24', 963, 456),
                                                          ('POI 25', 'Description 25', 147, 654),
                                                          ('POI 26', 'Description 26', 258, 852),
                                                          ('POI 27', 'Description 27', 369, 951),
                                                          ('POI 28', 'Description 28', 471, 357),
                                                          ('POI 29', 'Description 29', 582, 456),
                                                          ('POI 30', 'Description 30', 693, 654),
                                                          ('POI 31', 'Description 31', 123, 456),
                                                          ('POI 32', 'Description 32', 789, 321),
                                                          ('POI 33', 'Description 33', 654, 987),
                                                          ('POI 34', 'Description 34', 111, 222),
                                                          ('POI 35', 'Description 35', 333, 444),
                                                          ('POI 36', 'Description 36', 555, 666),
                                                          ('POI 37', 'Description 37', 777, 888),
                                                          ('POI 38', 'Description 38', 999, 000),
                                                          ('POI 39', 'Description 39', 246, 135),
                                                          ('POI 40', 'Description 40', 789, 654),
                                                          ('POI 41', 'Description 41', 852, 741),
                                                          ('POI 42', 'Description 42', 963, 852),
                                                          ('POI 43', 'Description 43', 147, 258),
                                                          ('POI 44', 'Description 44', 369, 741),
                                                          ('POI 45', 'Description 45', 753, 951),
                                                          ('POI 46', 'Description 46', 852, 963),
                                                          ('POI 47', 'Description 47', 159, 357),
                                                          ('POI 48', 'Description 48', 258, 456),
                                                          ('POI 49', 'Description 49', 357, 654),
                                                          ('POI 50', 'Description 50', 456, 852);
